books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add_books/', views.add_books, name='add_books'),
    path('book/<int:id>', views.book, name = 'book')
]

flashcard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('new_flashcard/', views.new_flashcard, name='new_flashcard'),
    path('delete_flashcard/<int:id>', views.delete_flashcard, name='delete_flashcard'),
    path('start_challenge/', views.start_challenge, name='start_challenge'),
    path('list_challenge/', views.list_challenge, name='list_challenge'),
    path('challenge/<int:id>', views.challenge, name='challenge'),
    path('to_respond_flashcard/<int:id>/', views.to_respond_flashcard, name='to_respond_flashcard'),
]

study_async/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('flashcard/', include('flashcard.urls')),
    path('reports/', include('reports.urls')),
    path('books/',include('books.urls')),
    path('', views.home, name="home")
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category (models.Model):
    name = models.CharField(max_length = 20)
    def __str__(self):
        return self.name
    
class Flashcard(models.Model):
    DIFFICULTE_CHOICES = (('D', 'Difícil'), ('M', 'Médio'), ('F', 'Fácil'))
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    question = models.CharField(max_length=100)
    response = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    difficulte = models.CharField(max_length=1, choices=DIFFICULTE_CHOICES)
    def __str__(self):
        return self.question
    @property
    def css_difficulte(self):
        if self.difficulte == 'F':
            return 'flashcard-facil'
        elif self.difficulte == 'M':
            return 'flashcard-medio'
        elif self.difficulte == 'D':
            return 'flashcard-dificil'

class FlashcardChallenge(models.Model):
    flashcard = models.ForeignKey(Flashcard, on_delete=models.DO_NOTHING)
    answered = models.BooleanField(default=False)
    got_it_right = models.BooleanField(default=False)
    def __str__(self):
        return self.flashcard.question
    
class Challenge(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=100)
    category = models.ManyToManyField(Category)
    quantity_questions = models.IntegerField()
    difficulte = models.CharField(
    max_length=1, choices=Flashcard.DIFFICULTE_CHOICES
    )
    flashcards = models.ManyToManyField(FlashcardChallenge)
    def __str__(self):
        return self.title

flashcard/views.py
from django.shortcuts import render, redirect
from .models import Category, Flashcard, Challenge, FlashcardChallenge
from django.contrib.messages import constants
from django.contrib import messages
from django.http import HttpResponse, Http404

# Create your views here.
def new_flashcard(request):
    if not request.user.is_authenticated:
        return redirect('/users/login')
    
    if request.method == 'GET':
        categorys = Category.objects.all()
        difficultes = Flashcard.DIFFICULTE_CHOICES
        flashcards = Flashcard.objects.filter(user = request.user)
        category_filter = request.GET.get('categoria')
        difficulte_filter = request.GET.get('dificuldade')
        if category_filter:
            flashcards = flashcards.filter(category__id = category_filter)
        if difficulte_filter:
            flashcards = flashcards.filter(difficulte = difficulte_filter)
        return render(request, 'new_flashcard.html', {'categorys': categorys, 'difficultes': difficultes, 'flashcards': flashcards})
    
    elif request.method == 'POST':
        question = request.POST.get('pergunta')
        response = request.POST.get('resposta')
        category = request.POST.get('categoria')
        difficulte = request.POST.get('dificuldade')

        if len(question.strip()) == 0 or len(response.strip()) == 0:
            messages.add_message(request, constants.ERROR, 'Preencha os campos de pergunta e resposta')
            return redirect('/flashcard/new_flashcard/')
        
        flashcard = Flashcard(
            user = request.user,
            question = question,
            response = response,
            category_id = category,
            difficulte = difficulte
        )

        flashcard.save()
        messages.add_message(request, constants.SUCCESS, 'Flashcard cadastrado com sucesso')
        return redirect('/flashcard/new_flashcard')

def delete_flashcard(request, id):
    flashcard = Flashcard.objects.get(id = id, user = request.user)
    flashcard.delete()
    messages.add_message(request, constants.SUCCESS, 'flashcard deletado com sucesso')
    return redirect('/flashcard/new_flashcard')

def start_challenge(request):
    if request.method == 'GET':
        categorys = Category.objects.all()
        difficultes = Flashcard.DIFFICULTE_CHOICES
        return render(request, 'start_challenge.html', {'categorys': categorys, 'difficultes': difficultes})
    elif request.method == "POST":
        title = request.POST.get('titulo')
        categorys = request.POST.getlist('categoria')
        difficulte = request.POST.get('dificuldade')
        quantity_questions = request.POST.get('qtd_perguntas')
        challenge = Challenge(
            user = request.user,
            title = title,
            difficulte = difficulte,
            quantity_questions = quantity_questions
        )
        print(challenge.difficulte)
        challenge.save()

        challenge.category.add(*categorys)

        flashcards = (
            Flashcard.objects.filter(user=request.user)
            .filter(difficulte=difficulte)
            .filter(category_id__in=categorys)
            .order_by('?')
        )
        
        if flashcards.count() < int(quantity_questions):
            messages.add_message(request, constants.WARNING, 'nao tem essa quantidade de flashcards')
            return redirect('/flashcard/start_challenge')
        
        flashcards = flashcards[:int(quantity_questions)]
        for f in flashcards:
            flashcard_challenge = FlashcardChallenge(
                flashcard = f
            )
            flashcard_challenge.save()
            challenge.flashcards.add(flashcard_challenge)
        
        challenge.save()
        return redirect('/flashcard/list_challenge/')
    
def list_challenge(request):
    challenges = Challenge.objects.filter(user=request.user)
    categorys = Category.objects.all()
    difficultes = Flashcard.DIFFICULTE_CHOICES
    category_filter = request.GET.get('categoria')
    difficulte_filter = request.GET.get('dificuldade')
    if category_filter:
        challenges = challenges.filter(category__in=category_filter)
    if difficulte_filter:
        challenges = challenges.filter(difficulte = difficulte_filter)
    return render(
        request,
        'list_challenge.html',
        {
            'challenges': challenges,
            'categorys': categorys,
            'difficultes': difficultes
        },
    )

def challenge(request, id):
    challenge = Challenge.objects.get(id = id)
    if not challenge.user == request.user:
        raise Http404()
    if request.method == 'GET':
        categories = challenge.flashcards.values_list('flashcard__category__name', flat=True).distinct()
        got_it_right = challenge.flashcards.filter(answered = True).filter(got_it_right = True).count()
        miss = challenge.flashcards.filter(answered = True).filter(got_it_right = False).count()
        missing = challenge.flashcards.filter(answered = False).count()
        return render(request, 'challenge.html', {'challenge':challenge, 'got_it_right': got_it_right, 
                                                  'miss': miss, 'missing': missing, 'categories': categories})

def to_respond_flashcard(request, id):
    flashcard_challenge = FlashcardChallenge.objects.get(id=id)
    got_it_right = request.GET.get('acertou')
    challenge_id = request.GET.get('desafio_id')

    if not flashcard_challenge.flashcard.user == request.user:
        raise Http404()

    flashcard_challenge.answered = True
    flashcard_challenge.got_it_right = True if got_it_right == '1' else False
    flashcard_challenge.save()
    return redirect(f'/flashcard/challenge/{challenge_id}')

flashcard/templates/challenge.html
{% extends "base.html" %}
{% load static %}

{% block 'header' %}

    <link href="{% static 'users/css/register.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/new_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/start_challenge.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/challenge.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'header' %}


{% block 'content' %}
    {% include "partials/header.html" %}
     
    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <h3 class="fonte-secundaria" >Desafio iniciado</h3>
                {% for categorie in categories.all %}
                    <span class="badge-categoria">{{categorie}}</span>
                {% endfor %}
                <br>
                <br>
                <br>
                {% for flash in challenge.flashcards.all %}
                    <div class="box-new-flashcard {% if flash.answered %} op2 {% endif %}">
                        <div class="flashcard {{flash.flashcard.css_difficulte}}">

                            <div class="flashcard-categoria">
                                {{flash.flashcard.category}}
                            </div>
                            <br>
                            <br>
                            <div class="flashcard-box-item" onclick="flip_card({{flash.id}})">
                                <p class="flashcard-item">{{flash.flashcard.question}}</p>
                            </div>

                            {% if not flash.answered %}
                            <div class="responder">
                                <a href="{% url 'to_respond_flashcard' flash.id %}?acertou=0&desafio_id={{challenge.id}}"><i class='bx bxs-x-square icone-vermelho'></i></a>
                                <a href="{% url 'to_respond_flashcard' flash.id %}?acertou=1&desafio_id={{challenge.id}}"><i class='bx bxs-check-square icone-verde' ></i></a>
                            </div>
                            {% else %}
                            {% if flash.got_it_right %}
                                <span class="badge bg-success">Acertou</span>
                            {% else %}
                                <span class="badge bg-danger">Errou</span>
                            {% endif%}

                            {% endif %}
                            
                            
                        </div>
                        <div class="resposta-flashcard" id="{{flash.id}}">
                            {{flash.flashcard.response}}
                        </div>
                    </div>
                    <br>
                    <br>
                {% endfor %}

            </div>
            <div class="col-md">

                <h3 class="fonte-secundaria">Resultado</h3>
                <p class="fonte-p">Acertos: {{got_it_right}}</p>
                <p class="fonte-p">Erros: {{miss}}</p>
                <p class="fonte-p">Faltantes: {{missing}}</p>
                <br>
                <a class="btn-cadastro btn-desafio" href="{% url 'reports' challenge.id %}">Relatório detalhado</a>
            </div>
        </div>

    </div>
    <script src="{% static 'flashcard/js/script.js' %}"></script>
{% endblock 'content' %}

flashcard/templates/list_challenge.html
{% extends "base.html" %}
{% load static %}

{% block 'header' %}

    <link href="{% static 'users/css/register.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/new_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/start_challenge.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/challenge.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'header' %}


{% block 'content' %}
    {% include "partials/header.html" %}

    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <form action="{% url 'list_challenge' %}" method="GET">
                <label for="">Categoria</label>
                <select name="categoria" class="form-select">
                    <option value="">Todas as categorias</option>
                    {% for category in categorys %}
                    <option value="{{category.id}}">{{category.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-md">
                <label for="">Dificuldade</label>
                <select name="dificuldade" class="form-select">
                    <option value="">Todas as dificuldades</option>
                            {% for difficulte in difficultes %}
                                <option value="{{difficulte.0}}">{{difficulte.1}}</option>
                            {% endfor %}
                </select>
            </div>
            <div class="col-md">
                <br>
                <input type="submit" value="Filtrar" class="btn-cadastro">
                </form>
            </div>
        </div>
        <br>
        <br>
        <div class="box-listar">
            <table>
                <thead>
                  <tr>
                    <th scope="col">Desafio</th>
                    <th scope="col">Titulo</th>
                    <th scope="col">Dificuldade</th>
                    <th scope="col">Status</th>
                  </tr>
                </thead>
                <tbody>
                    {% for challenge in challenges %}
                        <tr class="linha">
                            <th><a href="{% url 'challenge' challenge.id %}">{{challenge.id}}</a></th>
                            <td>{{challenge.title}}</td>
                            <td>{{challenge.get_difficulte_display}}</td>
                            <td>{{challenge.status}}</td>
                        </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
    <script src="{% static 'flashcard/js/script.js' %}"></script>
{% endblock 'content' %}

flashcard/templates/new_flashcard.html
{% extends "base.html" %}
{% load static %}
{% block 'header' %}
<link href="{% static 'users/css/Register.css' %}" rel="stylesheet">
<link href="{% static 'flashcard/css/new_flashcard.css' %}" rel="stylesheet">
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<script src="{% static 'flashcard/js/script.js' %}""></script>
{% endblock 'header' %}
{% block 'content' %}
    {% include "partials/header.html" %}
    <div class="container">
        <br>
        <br>
        <div class="row">

            <div class="col-md">

                <div class="box-form">
                    <form action="{% url 'new_flashcard' %}" method="POST"> {% csrf_token %}
                        <h3>Novo flashcard</h3>
                        {% if messages %}
                        <br>
                        {% for message in messages %}
                        <section class="alert {{message.tags}}">
                            {{message}}
                        </section>
                        {% endfor %}
                        {% endif %}
                        <br>
                        <label>Pergunta</label>
                        <input type="text" class="form-control" placeholder="pergunta" name="pergunta">
                        <br>
                        <label>Resposta</label>
                        <textarea class="form-control" name="resposta"></textarea>
                        <br>
                        <div class="row">

                            <div class="col-md">
                                <label for="">Categoria</label>
                                <select class="form-select" name="categoria">
                                    {% for category in categorys %}
                                        <option value="{{category.id}}">{{category.name}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md">
                                <label for="">Dificuldade</label>
                                <select class="form-select" name="dificuldade">
                                    {% for difficulte in difficultes %}
                                        <option value="{{difficulte.0}}">{{difficulte.1}}</option>
                                    {% endfor %}
                                </select>
                            </div>

                        </div>
                        <br>
                        <input type="submit" value="Enviar" class="btn-cadastro">
                        <br>
                        <br>
                        <br>
                    </form>
                </div>
            </div>
            <div class="col-md">
                <form action="{% url 'new_flashcard' %}" method="GET">
                    <div class="row">
                        <div class="col-md">
                            <label for="">Categoria</label>
                            <select name="categoria" id="" class="form-select">
                                <option value="">Todas as categorias</option>
                                {% for category in categorys %}
                                <option value="{{category.id}}">{{category.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md">
                            <label for="">Dificuldade</label>
                            <select name="dificuldade" id="" class="form-select">
                                <option value="">Todas as dificuldades</option>
                                {% for difficulte in difficultes %}
                                    <option value="{{difficulte.0}}">{{difficulte.1}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md">
                            <br>
                            <input type="submit" style="width: 100%" value="Filtrar" class="btn-cadastro">
                        </div>
                    </div>
                </form>
                <br>
                <br>
                {% for flashcard in flashcards %}
                    <div class="box-new-flashcard" onclick="flip_card({{flashcard.id}})">
                        <div class="flashcard ">
                            <div class="flashcard-categoria">
                                {{flashcard.category}}
                            </div>
                            <a href="{% url 'delete_flashcard' flashcard.id %}"><i class='icone-exit bx bx-x-circle'></i></a>
                            <br>
                            <br>
                            <div class="flashcard-box-item">
                                <p class="flashcard-item">{{flashcard.question}}</p>
                            </div>
                        </div>
                        <div class="resposta-flashcard" id="{{flashcard.id}}">
                            {{flashcard.response}}
                        </div>
                    </div>
                {% endfor %}
                <br>
                <br>

            </div>
        </div>
    </div>
{% endblock 'content' %}

flashcard/templates/start_challenge.html
{% extends "base.html" %}
{% load static %}

{% block 'header' %}

    <link href="{% static 'users/css/register.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/new_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/start_challenge.css' %}" rel="stylesheet">

{% endblock 'header' %}


{% block 'content' %}
    {% include "partials/header.html" %}
    <div class="container ctx">
        <br>
        <br>
        <h2 class="fonte-principal">Iniciar desafio</h2>
        <p class="fonte-secundaria">Escolha as categorias e a dificuldade do desafio</p>
        <div class="row">
            
                <div class="col-md">
                    <form action="{% url 'start_challenge' %}" method="POST">{% csrf_token%}
                    <label for="">Titulo</label>
                    <input type="text" class="form-control" name="titulo">
                </div>
                <div class="col-md">
                    <label>Categoria</label>
                    <select name="categoria" class="form-select" multiple>
                        {% for category in categorys %}
                            <option value="{{category.id}}">
                                {{category.name}}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md">
                    <label>Dificuldade</label>
                    <select name="dificuldade" class="form-select">
                        {% for difficulte in difficultes %}
                            <option value="{{difficulte.0}}">
                                {{difficulte.1}}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col-md">
                    <label>Qtd questões</label>
                    <input type="number" class="form-control" name="qtd_perguntas">
                </div>
            
        </div>
        <br>
        <br>
        <input type="submit" class="btn-cadastro" value="Iniciar desafio">
        </form>
    </div>
{% endblock 'content' %}